import type { Metadata } from "next";
import { Rubik, Montserrat } from "next/font/google";
import "../styles/globals.scss";

import { AuthProvider } from "../context/authContext";

import Header from "@/src/components/header/header";
import Footer from "@/src/components/footer/footer";

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className} ${montserrat.variable}`}>
        <AuthProvider>
          <Header />
          <div className="content">{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
