import type { Metadata } from 'next'
import { Rubik, Montserrat } from 'next/font/google'
import '../styles/globals.scss'

import Header from '@/src/components/header/header'

const rubik = Rubik({ subsets: ['latin'], variable:"--font-rubik"  })
const montserrat = Montserrat({ subsets: ['latin'], variable:"--font-montserrat" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={`${rubik.className} ${montserrat.variable}`}>
        <div className='container'>
          <Header/>
          <div>{children}</div>
        </div>
        </body>
    </html>
  )
}
